//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.12 at 09:32:43 PM CEST 
//


package com.nalogzaprenos;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nalogzaprenos package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BrojRacuna_QNAME = new QName("http://nalogZaPrenos.com", "broj_racuna");
    private final static QName _PodaciODuznikuNalogodavcu_QNAME = new QName("http://nalogZaPrenos.com", "podaci_o_duzniku_nalogodavcu");
    private final static QName _PodaciOPoveriocuPrimaocu_QNAME = new QName("http://nalogZaPrenos.com", "podaci_o_poveriocu_primaocu");
    private final static QName _PodaciOZaduzenju_QNAME = new QName("http://nalogZaPrenos.com", "podaci_o_zaduzenju");
    private final static QName _PodaciOOdobrenju_QNAME = new QName("http://nalogZaPrenos.com", "podaci_o_odobrenju");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nalogzaprenos
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Iznos }
     * 
     */
    public Iznos createIznos() {
        return new Iznos();
    }

    /**
     * Create an instance of {@link TPodaci }
     * 
     */
    public TPodaci createTPodaci() {
        return new TPodaci();
    }

    /**
     * Create an instance of {@link GetNalogZaPrenosResponse }
     * 
     */
    public GetNalogZaPrenosResponse createGetNalogZaPrenosResponse() {
        return new GetNalogZaPrenosResponse();
    }

    /**
     * Create an instance of {@link NalogZaPrenos }
     * 
     */
    public NalogZaPrenos createNalogZaPrenos() {
        return new NalogZaPrenos();
    }

    /**
     * Create an instance of {@link PodaciOPrenosu }
     * 
     */
    public PodaciOPrenosu createPodaciOPrenosu() {
        return new PodaciOPrenosu();
    }

    /**
     * Create an instance of {@link GetNalogZaPrenosRequest }
     * 
     */
    public GetNalogZaPrenosRequest createGetNalogZaPrenosRequest() {
        return new GetNalogZaPrenosRequest();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nalogZaPrenos.com", name = "broj_racuna")
    public JAXBElement<String> createBrojRacuna(String value) {
        return new JAXBElement<String>(_BrojRacuna_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nalogZaPrenos.com", name = "podaci_o_duzniku_nalogodavcu")
    public JAXBElement<TLice> createPodaciODuznikuNalogodavcu(TLice value) {
        return new JAXBElement<TLice>(_PodaciODuznikuNalogodavcu_QNAME, TLice.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nalogZaPrenos.com", name = "podaci_o_poveriocu_primaocu")
    public JAXBElement<TLice> createPodaciOPoveriocuPrimaocu(TLice value) {
        return new JAXBElement<TLice>(_PodaciOPoveriocuPrimaocu_QNAME, TLice.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPodaci }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nalogZaPrenos.com", name = "podaci_o_zaduzenju")
    public JAXBElement<TPodaci> createPodaciOZaduzenju(TPodaci value) {
        return new JAXBElement<TPodaci>(_PodaciOZaduzenju_QNAME, TPodaci.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPodaci }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nalogZaPrenos.com", name = "podaci_o_odobrenju")
    public JAXBElement<TPodaci> createPodaciOOdobrenju(TPodaci value) {
        return new JAXBElement<TPodaci>(_PodaciOOdobrenju_QNAME, TPodaci.class, null, value);
    }

}
