//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 11:21:48 PM CEST 
//


package com.mt900;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mt900 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mt900
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetMT900Response }
     * 
     */
    public GetMT900Response createGetMT900Response() {
        return new GetMT900Response();
    }

    /**
     * Create an instance of {@link MT900 }
     * 
     */
    public MT900 createMT900() {
        return new MT900();
    }

    /**
     * Create an instance of {@link GetMT900Request }
     * 
     */
    public GetMT900Request createGetMT900Request() {
        return new GetMT900Request();
    }

}
