//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.12 at 09:32:43 PM CEST 
//


package com.mt102;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mt102 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PojedinacnoPlacanjeMT102_QNAME = new QName("http://mt102.com", "pojedinacnoPlacanjeMT102");
    private final static QName _ZaglavljeMT102_QNAME = new QName("http://mt102.com", "zaglavljeMT102");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mt102
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PojedinacnoPlacanjeMT102 }
     * 
     */
    public PojedinacnoPlacanjeMT102 createPojedinacnoPlacanjeMT102() {
        return new PojedinacnoPlacanjeMT102();
    }

    /**
     * Create an instance of {@link GetMT102Response }
     * 
     */
    public GetMT102Response createGetMT102Response() {
        return new GetMT102Response();
    }

    /**
     * Create an instance of {@link MT102 }
     * 
     */
    public MT102 createMT102() {
        return new MT102();
    }

    /**
     * Create an instance of {@link ZaglavljeMT102 }
     * 
     */
    public ZaglavljeMT102 createZaglavljeMT102() {
        return new ZaglavljeMT102();
    }

    /**
     * Create an instance of {@link GetMT102Request }
     * 
     */
    public GetMT102Request createGetMT102Request() {
        return new GetMT102Request();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PojedinacnoPlacanjeMT102 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mt102.com", name = "pojedinacnoPlacanjeMT102")
    public JAXBElement<PojedinacnoPlacanjeMT102> createPojedinacnoPlacanjeMT102(PojedinacnoPlacanjeMT102 value) {
        return new JAXBElement<PojedinacnoPlacanjeMT102>(_PojedinacnoPlacanjeMT102_QNAME, PojedinacnoPlacanjeMT102 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZaglavljeMT102 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mt102.com", name = "zaglavljeMT102")
    public JAXBElement<ZaglavljeMT102> createZaglavljeMT102(ZaglavljeMT102 value) {
        return new JAXBElement<ZaglavljeMT102>(_ZaglavljeMT102_QNAME, ZaglavljeMT102 .class, null, value);
    }

}
